### ISSUE TITLE
Any furture plans for development?

### ISSUE THREAD

**Issue by Rainer-Lang** [sdoward/RxGoogleMaps#3]

**Comment by sdoward** [comment]
@Rainer-Lang are you looking for something in particular? There is an open issue for streetviewpanorama but I am starting to think that would be better suited to a different library. Other than that the lib is feature complete but I do intend on updating it with future releases of google maps

**Comment by Rainer-Lang** [comment]
@sdoward No, it was only a general question. Thanks for your answer - and still maintaining the lib.
