### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by suhas-sm** [sdoward/RxGoogleMaps#4]
Instead of adding all the three dependencies in the consumer application, the same thing can be achieved but just adding:
`compile('com.sdoward:rxgooglemaps:0.2@aar'){
        transitive true
}`

and move the internal dependencies to the rxgooglemap's build.gradle ? What is your take on this ?

PS: Just went through the build.gradle script again and noticed provided. Hmm interesting. Planning to add gitter here ?

**Comment by sdoward** [comment]
To be honest I was a little unsure of the best approach for this. In the end, I thought it would be better or the consumers of the lib to be more declarative which the libraries that they depend on. However I am open to change if there is a good reason to.

No plans to use gitter as of yet. Do you think that I should? There hasn't been much conversation about this lib so i am not sure if make sense.
