### ISSUE TITLE
GoogleMaps object returns null even after subscribed and observed

### ISSUE THREAD

**Issue by aimanbaharum** [sdoward/RxGoogleMaps#6]
Hey, FRP and Maps beginner here, still learning. I'm not sure if this is the correct place to ask for this, I guess it is somewhat related. If not, sorry for going offtopic and just close it.

---

So, I'm using this library to show some markers on a map using [ClusterManager][2] utility. Here's what I had done,

In `onCreate`, I initialized `GoogleApiClient` to get current location via `LocationServices`.

    mGoogleApiClient = new GoogleApiClient.Builder(this)
            .addConnectionCallbacks(this)
            .addOnConnectionFailedListener(this)
            .addApi(LocationServices.API)
            .build();
    
    mCurrentLocation = LocationServices
            .FusedLocationApi.getLastLocation(mGoogleApiClient);

I'm also storing GoogleMap object in a variable inside `getMapReadyObservable` callback, which will be used by ClusterManager later on:

    subscriptions.add(mapObservableProvider.getMapReadyObservable()
            .subscribe(googleMap -> {
                this.googleMap = googleMap;
            }));

Initializing ClusterManager after the subscription has been made:

    ClusterManager<ClusterMarkerLocation> clusterManager = new ClusterManager<>(this, googleMap);
    
    ...
    
    clusterManager.addItem(new ClusterMarkerLocation(new LatLng(mCenterLocation.latitude + lat, mCenterLocation.longitude + lng)));

So here's my problem, after I compile and run on device, it throws an error saying that `googleMap` object is **null** even after I initialized ClusterManager after the `getMapReadyObservable` call (which is where GoogleMap object is stored in a variable). I'm not entirely sure what's the problem, maybe the flow implementation is wrong? On the other hand, if I put it inside the callback, it will throw an NPE on **LocationServices** object.

Is this a correct way of doing this? Can I `delay` the ClusterManager before it gets initialized? If so, how?

Any advice is much appreciated.

  [1]: https://github.com/sdoward/RxGoogleMaps
  [2]: https://developers.google.com/maps/documentation/android-api/utility/marker-clustering

**Comment by sdoward** [comment]
It's difficult for me to understand exactly what it happening. If you can, try and replicate  the issue with only using rxGoogleMaps, this way we would have a better understanding if the problem lies with this lib, with your implementation or with other libs. 

Can you replicate the issue when googleMap is passed as null down the stream? Once you do that we would have a better base to start.

How do you know when the subscribe has been called? Perhaps you could add the full class as a gist so I can see what is happening

**Comment by aimanbaharum** [comment]
Thanks for the reply. I also would like to clarify what I want to achieve with this. I just wanted to create a map with marker clustering. You can see the whole activity class in below gist.

https://gist.github.com/aimanbaharum/720ce207dbff2c751aee52e923249403

**Comment by sdoward** [comment]
Retrieving the map is an asynchronous operation and you are not waiting for it to be retrieved. The nice thing about RFP is that you can make classes without state, the idea of this lib is that you never really need to have a `googlemap` variable in your class. Provide 'Cluster Manager' as an observable and make everything a stream, that will probably solve you problem
